/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttendanceEntry {
  'principal' : Principal,
  'record' : AttendanceRecord,
}
export interface AttendanceRecord {
  'id' : bigint,
  'subjectName' : string,
  'date' : string,
  'createdAt' : bigint,
  'attended' : boolean,
  'subjectId' : bigint,
  'topicCovered' : string,
}
export interface DashboardStats {
  'taskStreak' : bigint,
  'todayAttendanceCount' : bigint,
  'pendingTasksCount' : bigint,
  'totalNotes' : bigint,
}
export interface Note {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'subjectName' : string,
  'aiPyqs' : string,
  'aiKeyTopics' : string,
  'subjectId' : bigint,
  'aiSummary' : string,
  'aiShortNotes' : string,
  'uploadedAt' : bigint,
}
export interface NoteEntry { 'principal' : Principal, 'note' : Note }
export interface Subject {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'level' : string,
}
export interface SubjectEntry { 'principal' : Principal, 'subject' : Subject }
export interface Task {
  'id' : bigint,
  'title' : string,
  'subjectName' : string,
  'createdAt' : bigint,
  'completed' : boolean,
  'dueDate' : string,
  'priority' : string,
}
export interface TaskEntry { 'principal' : Principal, 'task' : Task }
export interface UserEntry { 'principal' : Principal, 'profile' : UserProfile }
export interface UserProfile {
  'subjects' : Array<string>,
  'name' : string,
  'level' : string,
  'educationClass' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addNote' : ActorMethod<[bigint, string, string, string], bigint>,
  'addSubject' : ActorMethod<[string], bigint>,
  'addTask' : ActorMethod<[string, string, string, string], bigint>,
  'adminDeleteAttendance' : ActorMethod<[Principal, bigint], undefined>,
  'adminDeleteNote' : ActorMethod<[Principal, bigint], undefined>,
  'adminDeleteSubject' : ActorMethod<[Principal, bigint], undefined>,
  'adminDeleteTask' : ActorMethod<[Principal, bigint], undefined>,
  'adminGetAllAttendance' : ActorMethod<[], Array<AttendanceEntry>>,
  'adminGetAllNotes' : ActorMethod<[], Array<NoteEntry>>,
  'adminGetAllSubjects' : ActorMethod<[], Array<SubjectEntry>>,
  'adminGetAllTasks' : ActorMethod<[], Array<TaskEntry>>,
  'adminGetAllUsers' : ActorMethod<[], Array<UserEntry>>,
  'adminUpdateAttendance' : ActorMethod<
    [Principal, bigint, string, boolean],
    undefined
  >,
  'adminUpdateNote' : ActorMethod<
    [Principal, bigint, string, string, string],
    undefined
  >,
  'adminUpdateTask' : ActorMethod<
    [Principal, bigint, string, string, string, boolean],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteNote' : ActorMethod<[bigint], undefined>,
  'deleteSubject' : ActorMethod<[bigint], undefined>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'getAttendanceBySubject' : ActorMethod<[string], Array<AttendanceRecord>>,
  'getAttendanceRecords' : ActorMethod<[], Array<AttendanceRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getNotes' : ActorMethod<[], Array<Note>>,
  'getNotesBySubject' : ActorMethod<[bigint], Array<Note>>,
  'getSubjects' : ActorMethod<[], Array<Subject>>,
  'getTaskStreak' : ActorMethod<[], bigint>,
  'getTasks' : ActorMethod<[], Array<Task>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logAttendance' : ActorMethod<
    [bigint, string, string, string, boolean],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setUserProfile' : ActorMethod<
    [string, string, [] | [string], Array<string>],
    undefined
  >,
  'updateAttendanceRecord' : ActorMethod<[bigint, string, boolean], undefined>,
  'updateNoteAI' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
  'updateTaskStatus' : ActorMethod<[bigint, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];