/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const AttendanceRecord = IDL.Record({
  'id' : IDL.Nat,
  'subjectName' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'attended' : IDL.Bool,
  'subjectId' : IDL.Nat,
  'topicCovered' : IDL.Text,
});
export const AttendanceEntry = IDL.Record({
  'principal' : IDL.Principal,
  'record' : AttendanceRecord,
});
export const Note = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'subjectName' : IDL.Text,
  'aiPyqs' : IDL.Text,
  'aiKeyTopics' : IDL.Text,
  'subjectId' : IDL.Nat,
  'aiSummary' : IDL.Text,
  'aiShortNotes' : IDL.Text,
  'uploadedAt' : IDL.Int,
});
export const NoteEntry = IDL.Record({
  'principal' : IDL.Principal,
  'note' : Note,
});
export const Subject = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'level' : IDL.Text,
});
export const SubjectEntry = IDL.Record({
  'principal' : IDL.Principal,
  'subject' : Subject,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'subjectName' : IDL.Text,
  'createdAt' : IDL.Int,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Text,
  'priority' : IDL.Text,
});
export const TaskEntry = IDL.Record({
  'principal' : IDL.Principal,
  'task' : Task,
});
export const UserProfile = IDL.Record({
  'subjects' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'level' : IDL.Text,
  'educationClass' : IDL.Opt(IDL.Text),
});
export const UserEntry = IDL.Record({
  'principal' : IDL.Principal,
  'profile' : UserProfile,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DashboardStats = IDL.Record({
  'taskStreak' : IDL.Nat,
  'todayAttendanceCount' : IDL.Nat,
  'pendingTasksCount' : IDL.Nat,
  'totalNotes' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addNote' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addSubject' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'addTask' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'adminDeleteAttendance' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'adminDeleteNote' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'adminDeleteSubject' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'adminDeleteTask' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'adminGetAllAttendance' : IDL.Func([], [IDL.Vec(AttendanceEntry)], ['query']),
  'adminGetAllNotes' : IDL.Func([], [IDL.Vec(NoteEntry)], ['query']),
  'adminGetAllSubjects' : IDL.Func([], [IDL.Vec(SubjectEntry)], ['query']),
  'adminGetAllTasks' : IDL.Func([], [IDL.Vec(TaskEntry)], ['query']),
  'adminGetAllUsers' : IDL.Func([], [IDL.Vec(UserEntry)], ['query']),
  'adminUpdateAttendance' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'adminUpdateNote' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'adminUpdateTask' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteNote' : IDL.Func([IDL.Nat], [], []),
  'deleteSubject' : IDL.Func([IDL.Nat], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'getAttendanceBySubject' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getAttendanceRecords' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getNotesBySubject' : IDL.Func([IDL.Nat], [IDL.Vec(Note)], ['query']),
  'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'getTaskStreak' : IDL.Func([], [IDL.Nat], ['query']),
  'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logAttendance' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'updateAttendanceRecord' : IDL.Func([IDL.Nat, IDL.Text, IDL.Bool], [], []),
  'updateNoteAI' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateTaskStatus' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const AttendanceRecord = IDL.Record({
    'id' : IDL.Nat,
    'subjectName' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'attended' : IDL.Bool,
    'subjectId' : IDL.Nat,
    'topicCovered' : IDL.Text,
  });
  const AttendanceEntry = IDL.Record({
    'principal' : IDL.Principal,
    'record' : AttendanceRecord,
  });
  const Note = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'subjectName' : IDL.Text,
    'aiPyqs' : IDL.Text,
    'aiKeyTopics' : IDL.Text,
    'subjectId' : IDL.Nat,
    'aiSummary' : IDL.Text,
    'aiShortNotes' : IDL.Text,
    'uploadedAt' : IDL.Int,
  });
  const NoteEntry = IDL.Record({ 'principal' : IDL.Principal, 'note' : Note });
  const Subject = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'level' : IDL.Text,
  });
  const SubjectEntry = IDL.Record({
    'principal' : IDL.Principal,
    'subject' : Subject,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'subjectName' : IDL.Text,
    'createdAt' : IDL.Int,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Text,
    'priority' : IDL.Text,
  });
  const TaskEntry = IDL.Record({ 'principal' : IDL.Principal, 'task' : Task });
  const UserProfile = IDL.Record({
    'subjects' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'level' : IDL.Text,
    'educationClass' : IDL.Opt(IDL.Text),
  });
  const UserEntry = IDL.Record({
    'principal' : IDL.Principal,
    'profile' : UserProfile,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DashboardStats = IDL.Record({
    'taskStreak' : IDL.Nat,
    'todayAttendanceCount' : IDL.Nat,
    'pendingTasksCount' : IDL.Nat,
    'totalNotes' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addNote' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addSubject' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'addTask' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'adminDeleteAttendance' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'adminDeleteNote' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'adminDeleteSubject' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'adminDeleteTask' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'adminGetAllAttendance' : IDL.Func(
        [],
        [IDL.Vec(AttendanceEntry)],
        ['query'],
      ),
    'adminGetAllNotes' : IDL.Func([], [IDL.Vec(NoteEntry)], ['query']),
    'adminGetAllSubjects' : IDL.Func([], [IDL.Vec(SubjectEntry)], ['query']),
    'adminGetAllTasks' : IDL.Func([], [IDL.Vec(TaskEntry)], ['query']),
    'adminGetAllUsers' : IDL.Func([], [IDL.Vec(UserEntry)], ['query']),
    'adminUpdateAttendance' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'adminUpdateNote' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'adminUpdateTask' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteNote' : IDL.Func([IDL.Nat], [], []),
    'deleteSubject' : IDL.Func([IDL.Nat], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'getAttendanceBySubject' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getAttendanceRecords' : IDL.Func(
        [],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getNotesBySubject' : IDL.Func([IDL.Nat], [IDL.Vec(Note)], ['query']),
    'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'getTaskStreak' : IDL.Func([], [IDL.Nat], ['query']),
    'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logAttendance' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'updateAttendanceRecord' : IDL.Func([IDL.Nat, IDL.Text, IDL.Bool], [], []),
    'updateNoteAI' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateTaskStatus' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };